### ISSUE TITLE
Extend check_schema to include input data inconsistencies.

### ISSUE THREAD

**Issue by ggsdc** [baobabsoluciones/cornflow-server#100]
**Is your feature request related to a problem? Please describe.**
I would like to set up input data checks that check even if the problem is feasible before the solver is called.

**Describe the solution you'd like**
A way to include these checks after the schema has been validated

**Describe alternatives you've considered**
Let the solver find that the problem is unfeasible, but this can take time and maybe give back a difficult error message to decipher, while if we can narrow what the inconsistency is beforehand it can be handled better.

This has been talked in PR baobabsoluciones/cornflow-dags#24

**Comment by marioncottard** [comment]
@ggsdc Do we consider that this method should be mandatory or should we let it be optional?

**Comment by ggsdc** [comment]
It should be optional.

I guess that the default one in cornflow-client should give back an empty dict, and if the method is defined in the instance of the model, then that method is used and it gives back a dict with the data inconsistencies

If the dict is not empty, then the solve method should stop, cause some data inconsistencies have been found so solving the model does not make sense.

Then later I will implement that said dict is sent back to cornflow so that it can be reported to the user.

**Comment by marioncottard** [comment]
Okay it makes sense, thanks

**Comment by pchtsp** [comment]
If it's any guide, I've started to use a "check()" method in my instance to
see if it's "consistent". This can include if the data makes sense (master
tables have all the required indices) or if the instance is infeasible.
Alternatively, "data consistency" could be separated from "feasibility"
with two new methods. Something like "is_valid()" and "is_feasible()".

F.

**Comment by marioncottard** [comment]
Okay, this helps, thank you!
