### ISSUE TITLE
Changes to Facility Location dag

### ISSUE THREAD

**Issue by ggsdc** [baobabsoluciones/cornflow-server#124]
Modify the data structure so we that the different levels of warehouses are on the same table with a level property which can be defined as a master table as well.

This should allow to be able to have as many levels as we want, being the model more flexible.

**Comment by ggsdc** [comment]
@marioncottard with PR closed (https://github.com/baobabsoluciones/cornflow-dags/pull/74) can we close the issue as well?

**Comment by marioncottard** [comment]
Yes, we can close it
