### ISSUE TITLE
Check if token is valid

### ISSUE THREAD

**Issue by ggsdc** [baobabsoluciones/cornflow-server#142]
When reopening the application after the token has expired, the UI thinks it is still valid, but it is not, so a log out- go in is necessary.

Try to have it detect automatically if the token is not valid and in case that it is, have the option to log in directly

**Comment by marioncottard** [comment]
Does it make sense to have an endpoint for this on the server, that given a token, checks if it is valid or not? It can probably be done in other ways but I think this would be the cleanest way

**Comment by ggsdc** [comment]
> Does it make sense to have an endpoint for this on the server, that given a token, checks if it is valid or not? It can probably be done in other ways but I think this would be the cleanest way

It makes sense, I will update the tags so that a change is also made on cornflow-server to have and endpoint that just checks token validity, so that we can have the cornflow-app  check against it.

We should also see if it make sense to re-issue tokens in some instances to extend its "life"
