### ISSUE TITLE
Send email if password is missing, forgotten or corrupted

### ISSUE THREAD

**Issue by ggsdc** [baobabsoluciones/cornflow-server#164]
**Is your feature request related to a problem? Please describe.**
If there is a problem with the password of a user, but the user is in the database, cornflow should be able to send an email with a temp password that should help the user log in in order to change the password.

**Comment by marioncottard** [comment]
Does cornflow-server already have an email address?

**Comment by ggsdc** [comment]
We do not have one, but I have to see with David how we could set up one.
