### ISSUE TITLE
cornflow-client to_excel function uses `self.data` instead of `self.to_json()`

### ISSUE THREAD

**Issue by pchtsp** [baobabsoluciones/cornflow-server#216]
In the following lines:
https://github.com/baobabsoluciones/cornflow-client/blob/3f5a55f6f3fec1c3d02050ae2c62eba4c592d439/cornflow_client/core/instance_solution.py#L150-L151

A reference is done to `self.data` is done. But, the format of `self.data` is not standard. Just as with `from_excel` function returns the `self.from_dict(tables)`. the `to_excel` function should use `self.to_json()` method to iterate over the standardized tables of the data.

I think that it would be a good idea to add unittests so this doesn't slip again.

**Comment by ggsdc** [comment]
This will be fixed on https://github.com/baobabsoluciones/cornflow-client/pull/38 that is adding new test coverage (mainly to the cornflow client part, as it was not tested on the repo)
