### ISSUE TITLE
Control dag-level permissions in cornflow / airflow

### ISSUE THREAD

**Issue by pchtsp** [baobabsoluciones/cornflow-server#80]
**Is your feature request related to a problem? Please describe.**
Sometimes I'm a user who should not have access to certain solvers.

**Describe the solution you'd like**
I would like to be able to assign dag permissions to roles so only certain users would have access to certain dags/solvers.

**Describe alternatives you've considered**
Maybe we could store that in airflow and then cornflow would then use the cornflow user to get the dag information from airflow?
https://airflow.apache.org/docs/apache-airflow/stable/security/access-control.html#dag-level-role

**Comment by ggsdc** [comment]
Couldn't we implement this with user group? And the group the user belongs
to, indicates the dags the user have access to, that way they can not even
create an instance pointing to that schema.

**Comment by pchtsp** [comment]
It's possible and it's true we have talked about it.

Currently, cornflow does not have a list of avaliable dags. If we decide to
keep the dags only in airflow, then maybe it makes sense to control access
there. That way cornflow asks airflow (as it does now) for information on
dags. This implies we would need to replicate cornflows roles in airflow.

If we decide to create a dag catalog in cornflow that is synced with
airflow, then we could give permission at the dag level.
This implies that we would have to replicate airflow dag information in
cornflow.

There are probably other factors that I'm not thinking of that are
relevant.

**Comment by ggsdc** [comment]
Should be closed with #182

**Comment by ggsdc** [comment]
Cornflow-admin changes to be made on issue #198

**Comment by ggsdc** [comment]
Solved, missing cornflow-admin update
